---
title: Démarrer avec Minecraft Pi
hero_image: images/banner.png
description: Obtenir une première impression de la programmation du monde de Minecraft
original_url: https://raspberrypi.org/learning/getting-started-with-minecraft-pi
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Ce dont tu auras besoin
  - 
    title: Démarrer avec Minecraft Pi
  - 
    title: Exécuter Minecraft
  - 
    title: Utiliser l'interface de programmation Python
  - 
    title: Laisser tomber des blocs en marchant
  - 
    title: Jouer avec des blocs TNT
  - 
    title: S'amuser avec de la lave qui coule.
  - 
    title: Et ensuite ?
